site_name: INSA 生存指南
site_author: LapinRobin

repo_name: INSA-Survival-Guide
repo_url: https://github.com/LapinRobin/INSA-Survival-Guide

copyright: Copyright &copy; <script>document.write(new Date().getFullYear());</script> <a href="https://github.com/LapinRobin" target="_blank" rel="noopener noreferrer">LapinRobin</a>

theme:
  name: material
  custom_dir: overrides
  
  language: zh

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - search.share
    - search.suggest
    - navigation.footer
    - content.code.annotate

  

   

markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables



extra:
  analytics:
    provider: google
    property: G-5BFWX5GWRG

nav:
  - 前言: "index.md"
  - 赴法前准备: "赴法前准备.md"
  - 生存: 
    - 必办事项: "生存/必办事项.md"
    - 衣食住行: "生存/衣食住行.md"
    - 个人安全: "生存/个人安全.md"
  - 学习: 
    - 课程概况: "学习/课程概况.md"
    - 预备课程: "学习/预备课程.md"
    - 专业课程: "学习/专业课程.md"
    - 交换 | 双学位: "学习/交换|双学位.md"
  - 实习: 
    - 实习概况: "实习/实习概况.md"
    - 工人实习: "实习/工人实习.md"
    - 专业实习: "实习/专业实习.md"
  # - 生活: 
    # - 旅行: "生活/旅行.md"
  - 隐藏: 
    - 润学: "隐藏/润学.md"
  
  



